W7/D5/RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do 
    resources :subs, only: [:edit]
  end
  resource :session, only:[:new, :create, :destroy]
  resources :subs
end

W7/D5/RedditClone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :sub_id, presence: true
  validates :url, uniqueness: true

  belongs_to :sub,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Sub

  belongs_to :author,
  through: :sub,
  source: :moderator

  

  

  
end

W7/D5/RedditClone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true
  validates :title, :moderator_id, uniqueness:true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :posts,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Post

end

W7/D5/RedditClone/app/models/user.rb
class User < ApplicationRecord

  attr_reader :password
  after_initialize :ensure_session_token

  validates :username, :session_token, :password_digest, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6}, allow_nil: true

    has_many :subs,
      primary_key: :id,
      foreign_key: :moderator_id,
      class_name: :Sub

    has_many :posts,
     through: :subs,
     source: :posts

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_valid_password?(password)
      return user
    else
      nil
    end
  end

end

W7/D5/RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

W7/D5/RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_in, only: [:destroy]
  
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Username or Password"]
      redirect_to new_session_url
    end
  end

  def destroy
    logout
    flash[:messages] = ["Succesfully logged out"]
    redirect_to new_session_url
  end


end

W7/D5/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    
    if @sub.save
      redirect_to sub_url(@sub.id)
    else
      flash.now[:errors] = ["Invalid title"]
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    if current_user.id == @sub.moderator_id
      render :edit
    else
      flash.now[:errors] = ["Only moderator for this sub can edit"]
      redirect_to sub_url(@sub.id)
    end
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub.id)
    else
      flash.now[:errors] = ["Invalid title"]
      render :edit
    end
  end

  def sub_params
    params.require(:subs).permit(:title, :description)
  end




end

W7/D5/RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, except:[:new, :create]

  def index 
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user
      login(@user)
      redirect_to users_url
    else
      flash.now[:errors] = ["Invalid username or password!"]
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid username or password!"]
      render :edit
    end
  end 

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W7/D5/RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7/D5/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

W7/D5/RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

W7/D5/RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if !current_user.nil? %>
  
  <form action="<%=session_url%>" method="post">
  <input type="hidden" name="_method" value="DELETE">
   <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
   <input type="submit" value="Log Out">
  </form>
  <% else %>
  <form action="<%=new_user_url%>" method="get">
  <input type="submit" value="Create User">  
  </form>
  <% end %>
    <%= yield %>
  </body>
  <ol>
  <% if flash[:errors] != nil %>
  <% flash[:errors].each do |error| %>
  <li><%= error %></li>
  <% end %>
  <% end %>
  </ol>
</html>

W7/D5/RedditClone/app/views/users/edit.html.erb
<form action="<%=user_url%>" method="POST">
<input type="hidden" name="_method" value="PATCH">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<label> username
<input type="text" name="user[username]" value="<%=@user.username%>"></label>
<br/>

<label> password
<input type="password" name="user[password]" value=""></label>
<br/>

<input type="submit" value="EDIT USER">
</form>

W7/D5/RedditClone/app/views/users/index.html.erb
<h1>Users</h1>
<ol>
<% @users.each do |user|%>
<li><a href="<%=user_url(user.id)%>"><%= user.username%></a></li>
<%end%>
</ol>

W7/D5/RedditClone/app/views/users/new.html.erb
<form action="<%=users_url%>" method="POST">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<label> username
<input type="text" name="user[username]"></label>
<br/>

<label> password
<input type="password" name="user[password]"></label>
<br/>

<input type="submit" value="CREATE USER">
</form>

W7/D5/RedditClone/app/views/users/show.html.erb
<h1>Hello, <%= @user.username%></h1>

<a href="<%=subs_url%>">All Subs</a>